package com.melof10.challengevaregos.wsdl;

import java.util.List;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "transferenciasV2", targetNamespace = "http://ws.transferencias.banelco.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransferenciasV2 {


    /**
     * 
     * @param usuario
     * @param terminal
     * @return
     *     returns java.util.List<com.melof10.challengevaregos.soapclient.TicketDTO>
     */
    @WebMethod
    @WebResult(name = "ultimasTransferencias", targetNamespace = "")
    @RequestWrapper(localName = "getUltimasTransferencias", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.GetUltimasTransferencias")
    @ResponseWrapper(localName = "getUltimasTransferenciasResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.GetUltimasTransferenciasResponse")
    public List<TicketDTO> getUltimasTransferencias(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal);

    /**
     * 
     * @param transferencia
     * @param usuario
     * @param terminal
     * @return
     *     returns com.melof10.challengevaregos.soapclient.TicketDTO
     */
    @WebMethod
    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "transferirConCuenta", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.TransferirConCuenta")
    @ResponseWrapper(localName = "transferirConCuentaResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.TransferirConCuentaResponse")
    public TicketDTO transferirConCuenta(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal,
        @WebParam(name = "transferencia", targetNamespace = "")
        TransferenciaDTO transferencia);

    /**
     * 
     * @param cuentaOrigen
     * @param alias
     * @param usuario
     * @param terminal
     * @return
     *     returns com.melof10.challengevaregos.soapclient.TitularidadExtendidoDTO
     */
    @WebMethod
    @WebResult(name = "titularidadExtendido", targetNamespace = "")
    @RequestWrapper(localName = "consultarDatosTitularidadExtendido", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.ConsultarDatosTitularidadExtendido")
    @ResponseWrapper(localName = "consultarDatosTitularidadExtendidoResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.ConsultarDatosTitularidadExtendidoResponse")
    public TitularidadExtendidoDTO consultarDatosTitularidadExtendido(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal,
        @WebParam(name = "cuentaOrigen", targetNamespace = "")
        CuentaDTO cuentaOrigen,
        @WebParam(name = "alias", targetNamespace = "")
        String alias);

    /**
     * 
     * @param item
     * @param usuario
     * @param terminal
     */
    @WebMethod
    @RequestWrapper(localName = "modificarCBUEnAgenda", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.ModificarCBUEnAgenda")
    @ResponseWrapper(localName = "modificarCBUEnAgendaResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.ModificarCBUEnAgendaResponse")
    public void modificarCBUEnAgenda(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal,
        @WebParam(name = "item", targetNamespace = "")
        AgendaCBUDTO item);

    /**
     * 
     * @param item
     * @param usuario
     * @param terminal
     */
    @WebMethod
    @RequestWrapper(localName = "agregarCBUEnAgenda", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.AgregarCBUEnAgenda")
    @ResponseWrapper(localName = "agregarCBUEnAgendaResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.AgregarCBUEnAgendaResponse")
    public void agregarCBUEnAgenda(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal,
        @WebParam(name = "item", targetNamespace = "")
        AgendaCBUDTO item);

    /**
     * 
     * @param usuario
     * @param terminal
     * @return
     *     returns java.util.List<com.melof10.challengevaregos.soapclient.AgendaCBUDTO>
     */
    @WebMethod
    @WebResult(name = "agendaCBU", targetNamespace = "")
    @RequestWrapper(localName = "getAgendaCBU", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.GetAgendaCBU")
    @ResponseWrapper(localName = "getAgendaCBUResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.responses.GetAgendaCBUResponse")
    public List<AgendaCBUDTO> getAgendaCBU(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal);

    /**
     * 
     * @param cuentaOrigen
     * @param usuario
     * @param terminal
     * @param cbuDestino
     * @return
     *     returns com.melof10.challengevaregos.soapclient.TitularidadDTO
     */
    @WebMethod
    @WebResult(name = "titularidad", targetNamespace = "")
    @RequestWrapper(localName = "consultarDatosTitularidad", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.ConsultarDatosTitularidad")
    @ResponseWrapper(localName = "consultarDatosTitularidadResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.ConsultarDatosTitularidadResponse")
    public TitularidadDTO consultarDatosTitularidad(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal,
        @WebParam(name = "cuentaOrigen", targetNamespace = "")
        CuentaDTO cuentaOrigen,
        @WebParam(name = "cbuDestino", targetNamespace = "")
        String cbuDestino);

    /**
     * 
     * @param item
     * @param usuario
     * @param terminal
     */
    @WebMethod
    @RequestWrapper(localName = "agregarCBUAliasEnAgenda", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.AgregarCBUAliasEnAgenda")
    @ResponseWrapper(localName = "agregarCBUAliasEnAgendaResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.AgregarCBUAliasEnAgendaResponse")
    public void agregarCBUAliasEnAgenda(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal,
        @WebParam(name = "item", targetNamespace = "")
        AgendaCBUAliasDTO item);

    /**
     * 
     * @param item
     * @param usuario
     * @param terminal
     */
    @WebMethod
    @RequestWrapper(localName = "modificarCBUAliasEnAgenda", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.ModificarCBUAliasEnAgenda")
    @ResponseWrapper(localName = "modificarCBUAliasEnAgendaResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.ModificarCBUAliasEnAgendaResponse")
    public void modificarCBUAliasEnAgenda(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal,
        @WebParam(name = "item", targetNamespace = "")
        AgendaCBUAliasDTO item);

    /**
     * 
     * @param alias
     * @param usuario
     * @param terminal
     */
    @WebMethod
    @RequestWrapper(localName = "borrarCBUAliasDeAgenda", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.BorrarCBUAliasDeAgenda")
    @ResponseWrapper(localName = "borrarCBUAliasDeAgendaResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.BorrarCBUAliasDeAgendaResponse")
    public void borrarCBUAliasDeAgenda(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal,
        @WebParam(name = "alias", targetNamespace = "")
        String alias);

    /**
     * 
     * @param cuenta
     * @param usuario
     * @param terminal
     * @return
     *     returns com.melof10.challengevaregos.soapclient.CbuAliasDTO
     */
    @WebMethod
    @WebResult(name = "cbuAlias", targetNamespace = "")
    @RequestWrapper(localName = "consultarCBUAlias", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.ConsultarCBUAlias")
    @ResponseWrapper(localName = "consultarCBUAliasResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.ConsultarCBUAliasResponse")
    public CbuAliasDTO consultarCBUAlias(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal,
        @WebParam(name = "cuenta", targetNamespace = "")
        CuentaDTO cuenta);

    /**
     * 
     * @param transferencia
     * @param datosOriginante
     * @param usuario
     * @param terminal
     * @return
     *     returns com.melof10.challengevaregos.soapclient.TicketDTO
     */
    @WebMethod
    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "transferirConDatosOriginante", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.TransferirConDatosOriginante")
    @ResponseWrapper(localName = "transferirConDatosOriginanteResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.TransferirConDatosOriginanteResponse")
    public TicketDTO transferirConDatosOriginante(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal,
        @WebParam(name = "transferencia", targetNamespace = "")
        TransferenciaDTO transferencia,
        @WebParam(name = "datosOriginante", targetNamespace = "")
        DatosOriginanteDTO datosOriginante);

    /**
     * 
     * @param usuario
     * @param terminal
     * @return
     *     returns java.util.List<com.melof10.challengevaregos.soapclient.AgendaCBUExtendidoDTO>
     */
    @WebMethod
    @WebResult(name = "agendaCBUExtendido", targetNamespace = "")
    @RequestWrapper(localName = "getAgendaCBUExtendido", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.GetAgendaCBUExtendido")
    @ResponseWrapper(localName = "getAgendaCBUExtendidoResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.GetAgendaCBUExtendidoResponse")
    public List<AgendaCBUExtendidoDTO> getAgendaCBUExtendido(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal);

    /**
     * 
     * @param nroTarjeta
     * @param usuario
     * @param terminal
     * @return
     *     returns com.melof10.challengevaregos.soapclient.DatosUsuarioDTO
     */
    @WebMethod
    @WebResult(name = "datosUsuario", targetNamespace = "")
    @RequestWrapper(localName = "validarUsuario", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.ValidarUsuario")
    @ResponseWrapper(localName = "validarUsuarioResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.ValidarUsuarioResponse")
    public DatosUsuarioDTO validarUsuario(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal,
        @WebParam(name = "nroTarjeta", targetNamespace = "")
        String nroTarjeta);

    /**
     * 
     * @param usuario
     * @param terminal
     * @return
     *     returns java.util.List<com.melof10.challengevaregos.soapclient.CuentaDTO>
     */
    @WebMethod
    @WebResult(name = "cuentas", targetNamespace = "")
    @RequestWrapper(localName = "getCuentas", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.GetCuentas")
    @ResponseWrapper(localName = "getCuentasResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.GetCuentasResponse")
    public List<CuentaDTO> getCuentas(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal);

    /**
     * 
     * @param cuenta
     * @param usuario
     * @param terminal
     */
    @WebMethod
    @RequestWrapper(localName = "consultarLimitesDisponibles", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.ConsultarLimitesDisponibles")
    @ResponseWrapper(localName = "consultarLimitesDisponiblesResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.ConsultarLimitesDisponiblesResponse")
    public void consultarLimitesDisponibles(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal,
        @WebParam(name = "cuenta", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<CuentaDTO> cuenta);

    /**
     * 
     * @param nroCBU
     * @param usuario
     * @param terminal
     */
    @WebMethod
    @RequestWrapper(localName = "borrarCBUDeAgenda", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.BorrarCBUDeAgenda")
    @ResponseWrapper(localName = "borrarCBUDeAgendaResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.BorrarCBUDeAgendaResponse")
    public void borrarCBUDeAgenda(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal,
        @WebParam(name = "nroCBU", targetNamespace = "")
        String nroCBU);

    /**
     * 
     * @param transferencia
     * @param usuario
     * @param terminal
     * @return
     *     returns com.melof10.challengevaregos.soapclient.TicketDTO
     */
    @WebMethod
    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "transferirConCBU", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.TransferirConCBU")
    @ResponseWrapper(localName = "transferirConCBUResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.TransferirConCBUResponse")
    public TicketDTO transferirConCBU(
        @WebParam(name = "usuario", targetNamespace = "")
        UsuarioDTO usuario,
        @WebParam(name = "terminal", targetNamespace = "")
        TerminalDTO terminal,
        @WebParam(name = "transferencia", targetNamespace = "")
        TransferenciaDTO transferencia);

    /**
     * 
     * @param mensaje
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "respuesta", targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://ws.transferencias.banelco.com/", className = "com.melof10.challengevaregos.soapclient.EchoResponse")
    public String echo(
        @WebParam(name = "mensaje", targetNamespace = "")
        String mensaje);

}
