package com.melof10.challengevaregos.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;
import org.springframework.stereotype.Component;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@Component
@WebServiceClient(name = "TransferenciasV2Service", targetNamespace = "http://ws.transferencias.banelco.com/", wsdlLocation = "file:/home/melof10/Documentos/Proyectos/challenge-varegos/src/main/resources/docs/PRISMA_TransferenciasService.wsdl")
public class TransferenciasV2Service extends Service {

    private final static URL TRANSFERENCIASV2SERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSFERENCIASV2SERVICE_EXCEPTION;
    private final static QName TRANSFERENCIASV2SERVICE_QNAME = new QName("http://ws.transferencias.banelco.com/", "TransferenciasV2Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/melof10/Documentos/Proyectos/challenge-varegos/src/main/resources/docs/PRISMA_TransferenciasService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSFERENCIASV2SERVICE_WSDL_LOCATION = url;
        TRANSFERENCIASV2SERVICE_EXCEPTION = e;
    }

    public TransferenciasV2Service() {
        super(__getWsdlLocation(), TRANSFERENCIASV2SERVICE_QNAME);
    }

    public TransferenciasV2Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSFERENCIASV2SERVICE_QNAME, features);
    }

    public TransferenciasV2Service(URL wsdlLocation) {
        super(wsdlLocation, TRANSFERENCIASV2SERVICE_QNAME);
    }

    public TransferenciasV2Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSFERENCIASV2SERVICE_QNAME, features);
    }

    public TransferenciasV2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransferenciasV2Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TransferenciasV2
     */
    @WebEndpoint(name = "TransferenciasV2Port")
    public TransferenciasV2 getTransferenciasV2Port() {
        return super.getPort(new QName("http://ws.transferencias.banelco.com/", "TransferenciasV2Port"), TransferenciasV2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransferenciasV2
     */
    @WebEndpoint(name = "TransferenciasV2Port")
    public TransferenciasV2 getTransferenciasV2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.transferencias.banelco.com/", "TransferenciasV2Port"), TransferenciasV2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSFERENCIASV2SERVICE_EXCEPTION!= null) {
            throw TRANSFERENCIASV2SERVICE_EXCEPTION;
        }
        return TRANSFERENCIASV2SERVICE_WSDL_LOCATION;
    }

}
